### ISSUE TITLE
Support yarn as package manager

### ISSUE THREAD

**Issue by martinjuhasz** [bifravst/package-layered-lambdas#377]
Currently package-layered-lambdas only supports npm as the package manager. My project initially used yarn, but i actually switched just because of this package. It would be nice if it could also support yarn.

From what i see the only things that are dependend on that, are the installation of dependencies using `npm ci` and usage of the `package-lock.json`s checksum as a hash.

Are there any plans to support this at some point? Or willing to accept an PR regarding this? If so, how would a selection of the manager look like? Automatic detection based on the lock file? Manual using a param when calling it?

Thanks for considering!

**Comment by coderbyheart** [comment]
Hei :wave: Martin, thank you for the suggestion. I could make the commands executed on install configurable through a plugin, so they can be configured. Could you kindly provide the yarn equivalent for these actions/files:

Lock file: `package-lock.json`
Installing dependencies: `npm ci --ignore-scripts --only=prod`

**Comment by martinjuhasz** [comment]
So for yarn these equivalents would be:
Lock file: `yarn.lock`
Installing depencendies: `yarn install --frozen-lockfile --ignore-scripts --production`

`--frozen-lockfile`:
If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass `--frozen-lockfile` flag ([docs](https://classic.yarnpkg.com/en/docs/cli/install)). Don’t generate a yarn.lock lockfile and fail if an update is needed ([docs](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile)).

`--ignore-scripts`:
Do not execute any scripts defined in the project package.json and its dependencies ([docs](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-scripts)).

`--production`:
Yarn will not install any package listed in devDependencies if the NODE_ENV environment variable is set to production. Use this flag to instruct Yarn to ignore NODE_ENV and take its production-or-not status from this flag instead ([docs](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-production-true-false)).

**Comment by coderbyheart** [comment]
@martinjuhasz can you check if it works for you?

`npm i @bifravst/package-layered-lambdas@3.13.0-support-yarn.1` 

and provide the config as mentioned here:

https://github.com/bifravst/package-layered-lambdas/pull/379/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R32

**Comment by martinjuhasz** [comment]
Thank you for this quick response! It works totally fine for me. Packages on first run, uses cache and updates when lock file is changed. 

The only thing that happens is that i get a lot of warning messages from yarn inside the console reporter. These are the typical unmet-dependency warnings that get displayed when installing. It seems that npm supresses these warnings by default when running in `ci` mode? Taking a quick look it seems there is no way for yarn to supress those messages (`--silent` doesn't work). Thats totally fine tho and not a problem of `package-layered-lambdas` but `yarn` itself.

Again thanks for the quick implementation!

**Comment by coderbyheart** [comment]
Thank you for testing the solution.
I agree that the yarn warnings seem to be a known issue: https://github.com/yarnpkg/yarn/issues/6672
